### PR TITLE
Add Odin Project to BeginnerResources.md

### PR DESCRIPTION
**Pull request by VariousWeapon**
Added the Odin Project to beginner resources. @degoeym

### CODE REVIEW

**Comment by degoeym** [comment]
What say you, @jaybobo ?

**Comment by jaybobo** [comment]
@degoeym i trust your judgment on this one heh ;)

**Comment by degoeym** [comment]
I'll try to look through some of the coursework this week to assess it.

**Comment by nickserv** [comment]
:+1:

**Comment by degoeym** [comment]
That a thumbs up to adding it, or a thumbs up to me saying I'll evaluate it this week? :P

**Comment by nickserv** [comment]
Adding it. :laughing:

**Comment by degoeym** [comment]
**_(nods head)**_ It is done.

**Pull request merged**
